Fix the issue #68 (ImportError: cannot import name return_values).
The issue happened because the method "return_values" has been removed from Ansible:
```
Github repo: https://github.com/ansible/ansible
commit aba4bed803fc783ea920798356eee196f7b56129
Author: Sam Doran <sdoran@redhat.com>
Date:   Mon Mar 4 17:02:44 2019 -0500

    Move _handle_no_log_values() out of basic.py (#48628)

    * Rename method and make private
    * Use is_iterable, combine transformations
    * Remove unused return_values from network modules
    * Improve docstrings in new functions
    * Add new PASS_VAR
    * Add unit tests for list_no_log_values
    * Fix unit tests for Python 2.6

-def return_values(obj):
-    """ Return native stringified values from datastructures.
-
-    For use with removing sensitive values pre-jsonification."""
-    if isinstance(obj, (text_type, binary_type)):
-        if obj:
-            yield to_native(obj, errors='surrogate_or_strict')
-        return
-    elif isinstance(obj, SEQUENCETYPE):
-        for element in obj:
-            for subelement in return_values(element):
-                yield subelement
-    elif isinstance(obj, Mapping):
-        for element in obj.items():
-            for subelement in return_values(element[1]):
-                yield subelement
-    elif isinstance(obj, (bool, NoneType)):
-        # This must come before int because bools are also ints
-        return
-    elif isinstance(obj, NUMBERTYPES):
-        yield to_native(obj, nonstring='simplerepr')
-    else:
-        raise TypeError('Unknown parameter type: %s, %s' % (type(obj), obj))
```